// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx1i5zhXcimR1a2cuHpVtrAXXvGHNzz38',
    appId: '1:712451979484:web:3c7a51b743c90f3e9d9c19',
    messagingSenderId: '712451979484',
    projectId: 'lpmi-manage-62617',
    authDomain: 'lpmi-manage-62617.firebaseapp.com',
    databaseURL: 'https://lpmi-manage-62617-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lpmi-manage-62617.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi8n4egWFYokhDmbTjV-pXRGkGUdC0OeE',
    appId: '1:712451979484:android:d170e3b3619adead9d9c19',
    messagingSenderId: '712451979484',
    projectId: 'lpmi-manage-62617',
    databaseURL: 'https://lpmi-manage-62617-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lpmi-manage-62617.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQZQWtaeBSNDiSn9RK9CkJgkRSAbUwSX0',
    appId: '1:712451979484:ios:7fddab1a4667026d9d9c19',
    messagingSenderId: '712451979484',
    projectId: 'lpmi-manage-62617',
    databaseURL: 'https://lpmi-manage-62617-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lpmi-manage-62617.appspot.com',
    iosBundleId: 'fr.ub.lpmimanage.lpmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQZQWtaeBSNDiSn9RK9CkJgkRSAbUwSX0',
    appId: '1:712451979484:ios:3f90788ac827abdd9d9c19',
    messagingSenderId: '712451979484',
    projectId: 'lpmi-manage-62617',
    databaseURL: 'https://lpmi-manage-62617-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lpmi-manage-62617.appspot.com',
    iosBundleId: 'fr.ub.lpmimanage.lpmi.RunnerTests',
  );
}
