// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD89LYeZj9XQWbfMhjbeQMc-mWt2re1RTM',
    appId: '1:50047905010:web:8ea706167630c5d10ab46b',
    messagingSenderId: '50047905010',
    projectId: 'lpmi-manage-f3cbd',
    authDomain: 'lpmi-manage-f3cbd.firebaseapp.com',
    storageBucket: 'lpmi-manage-f3cbd.appspot.com',
    measurementId: 'G-MMT5Q0WW5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTOB1dfFKDb-lvJWwSePUQ-ynTqCNs8wo',
    appId: '1:50047905010:android:794c6d870d5db2d20ab46b',
    messagingSenderId: '50047905010',
    projectId: 'lpmi-manage-f3cbd',
    storageBucket: 'lpmi-manage-f3cbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlXsfvkg6I7DTWmd5g9105XH6F42M5Q34',
    appId: '1:50047905010:ios:1cc15a5821047f300ab46b',
    messagingSenderId: '50047905010',
    projectId: 'lpmi-manage-f3cbd',
    storageBucket: 'lpmi-manage-f3cbd.appspot.com',
    iosBundleId: 'fr.ub.lpmimanage.lpmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlXsfvkg6I7DTWmd5g9105XH6F42M5Q34',
    appId: '1:50047905010:ios:b8fa97a89c4bcd5a0ab46b',
    messagingSenderId: '50047905010',
    projectId: 'lpmi-manage-f3cbd',
    storageBucket: 'lpmi-manage-f3cbd.appspot.com',
    iosBundleId: 'fr.ub.lpmimanage.lpmi.RunnerTests',
  );
}
